#!/bin/sh

. /etc/rc.subr

name=fuel_server
rcvar=fuel_server_enable
pidfile="/var/run/${name}.pid"

command="/usr/sbin/daemon" 
command_args="-P /var/run/${name}.pid /usr/local/bin/node /root/Fuel_Record/fuel-server/index.js" 

load_rc_config $name
run_rc_command "$1"