#!/bin/sh

. /etc/rc.subr

name=fuel_server
rcvar=fuel_server_enable

command="/usr/sbin/daemon" 
command_args="/usr/local/bin/node /root/Fuel_Record/fuel-server/index.js" 

load_rc_config $name
run_rc_command "$1"